### ISSUE TITLE
I wanna only get notification Whale Whatch Tab

### ISSUE THREAD

**Issue by 252furkan** [evilgenius786/kcc_moonarch_app_alert#1]
Salamun Aleykum bro 
I wanna only get notification Whale Whatch Tab. How can i do that ? Thank you

**Comment by evilgenius786** [comment]
Can you send the link of that?

**Comment by 252furkan** [comment]
i m talking about of that 
![image](https://user-images.githubusercontent.com/8388554/141137432-5007b7a1-b1de-4568-a32d-cbdb17647d63.png)

**Comment by evilgenius786** [comment]
Just change the XPATH from "Token events" to "Whale Watch".

**Comment by 252furkan** [comment]
i getting this error bro . I installed what you said. How can i fix it ? Thank you 
![image](https://user-images.githubusercontent.com/8388554/141369308-93c59046-44f7-433c-ad4b-c92e8b47c587.png)

**Comment by evilgenius786** [comment]
Send the script here so i can take a look.

**Comment by 252furkan** [comment]
i  justchanged telegram id etc. and i tried on Ubuntu but didnt work. Getting same error

![image](https://user-images.githubusercontent.com/8388554/142142898-fd697c39-46ce-452f-8942-fa549b13b0b4.png)

import json
import time
import traceback
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from telegram.ext import Updater

t = 1
timeout = 10

debug = False

headless = False
images = False
max = False

incognito = True

coins = ["", "<Loading...>"]
chat_id = -1001640640380
tkn = "Token"


def main():
    driver = getChromeDriver()
    updater = Updater(tkn, use_context=True)
    driver.get("https://kcc.moonarch.app/")
    while True:
        try:
            tbody = driver.find_elements_by_xpath('//tbody')[1]
            if "0 found recently" in driver.page_source:
                print('0 found recently')
            else:
                coin = getElement(tbody, '//td[@aria-colindex="3" and @class="tokenName"]').text.strip()
                if coin not in coins:
                    kcc = (tbody.find_element_by_xpath('./tr[1]/td[4]/div/a[1]').get_attribute(
                        'href').strip())
                    chart = (tbody.find_element_by_xpath('./tr[1]/td[4]/div/a[2]').get_attribute(
                        'href').strip())
                    koffeeswap = (
                        tbody.find_element_by_xpath('./tr[1]/td[4]/div/a[3]').get_attribute(
                            'href').strip())
                    data = {'name': coin, "kcc": kcc, "chart": chart, "koffeeswap": koffeeswap}
                    print(datetime.now(), "*New coin*", coin)
                    print(json.dumps(data, indent=4))
                    updater.bot.sendMessage(chat_id=chat_id, text=f"""<b>{data['name']}</b>
<a href="{data['kcc']}">KCC</a>
<a href="{data['koffeeswap']}">Koffeeswap</a>
<a href="{data['chart']}">Chart</a>""", parse_mode="html", disable_web_page_preview=True)
                    coins.append(coin)
                else:
                    print(datetime.now(), coin)
                time.sleep(1)
        except:
            traceback.print_exc()


def click(driver, xpath, js=False):
    if js:
        driver.execute_script("arguments[0].click();", getElement(driver, xpath))
    else:
        WebDriverWait(driver, timeout).until(EC.element_to_be_clickable((By.XPATH, xpath))).click()


def getElement(driver, xpath):
    return WebDriverWait(driver, timeout).until(EC.presence_of_element_located((By.XPATH, xpath)))


def sendkeys(driver, xpath, keys, js=False):
    if js:
        driver.execute_script(f"arguments[0].value='{keys}';", getElement(driver, xpath))
    else:
        getElement(driver, xpath).send_keys(keys)


def getChromeDriver(proxy=None):
    options = webdriver.ChromeOptions()
    if debug:
        # print("Connecting existing Chrome for debugging...")
        options.debugger_address = "127.0.0.1:9222"
    else:
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option("excludeSwitches", ["enable-logging"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument("--disable-blink-features")
        options.add_argument("--disable-blink-features=AutomationControlled")
    if not images:
        # print("Turning off images to save bandwidth")
        options.add_argument("--blink-settings=imagesEnabled=false")
    if headless:
        # print("Going headless")
        options.add_argument("--headless")
        options.add_argument("--window-size=1920x1080")
    if max:
        # print("Maximizing Chrome ")
        options.add_argument("--start-maximized")
    if proxy:
        # print(f"Adding proxy: {proxy}")
        options.add_argument(f"--proxy-server={proxy}")
    if incognito:
        # print("Going incognito")
        options.add_argument("--incognito")
    return webdriver.Chrome(options=options)


def getFirefoxDriver():
    options = webdriver.FirefoxOptions()
    if not images:
        # print("Turning off images to save bandwidth")
        options.set_preference("permissions.default.image", 2)
    if incognito:
        # print("Enabling incognito mode")
        options.set_preference("browser.privatebrowsing.autostart", True)
    if headless:
        # print("Hiding Firefox")
        options.add_argument("--headless")
        options.add_argument("--window-size=1920x1080")
    return webdriver.Firefox(options)


if __name__ == "__main__":
    main()

**Comment by 252furkan** [comment]
Fixed it but now i getting these errors :/ 
![image](https://user-images.githubusercontent.com/8388554/142195379-78da0546-c513-4cb9-bc98-3085c537b534.png)

**Comment by evilgenius786** [comment]
Yout bot token is invalid.

**Comment by 252furkan** [comment]
thank you so much bro

**Comment by evilgenius786** [comment]
My pleasure :)

**Comment by 252furkan** [comment]
coin = getElement(tbody, '//td[@aria-colindex="3" and @class="whaleName"]').text.strip()

bro i just changed here for get notify whale tabs but didnt work . what should i do ? Thank you
